language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=./RailroadCrossing/RailroadCrossing.ino
    - PLATFORMIO_CI_SRC=./TownshipManagement/TownshipManagement.ino

install:
    - pip install -U platformio

script:
    - platformio ci --board=uno --board=nanoatmega168 --board=nanoatmega328
